#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  deploy_shared_verifier.sh --verifier-sol <path> --contract-name <name> --rpc-url <url> --private-key <key>

Options:
  --verifier-sol   Solidity verifier file generated by bb
  --contract-name  Local filename alias for the copied verifier source (default: ZusVerifier)
  --rpc-url        RPC URL for deployment
  --private-key    Deployer private key
  -h, --help       Show this help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERIFIER_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

VERIFIER_SOL=""
GENERATED_CONTRACT_NAME=""
CONTRACT_NAME="ZusVerifier"
RPC_URL=""
PRIVATE_KEY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verifier-sol)
      VERIFIER_SOL="${2:-}"
      shift 2
      ;;
    --contract-name)
      CONTRACT_NAME="${2:-}"
      shift 2
      ;;
    --rpc-url)
      RPC_URL="${2:-}"
      shift 2
      ;;
    --private-key)
      PRIVATE_KEY="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${VERIFIER_SOL}" || -z "${RPC_URL}" || -z "${PRIVATE_KEY}" ]]; then
  echo "--verifier-sol, --rpc-url, and --private-key are required" >&2
  usage >&2
  exit 1
fi

VERIFIER_SOL="$(cd "$(dirname "${VERIFIER_SOL}")" && pwd)/$(basename "${VERIFIER_SOL}")"
if [[ ! -f "${VERIFIER_SOL}" ]]; then
  echo "Could not find verifier Solidity file at ${VERIFIER_SOL}" >&2
  exit 1
fi

if [[ ! "${CONTRACT_NAME}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "Invalid Solidity contract name: ${CONTRACT_NAME}" >&2
  exit 1
fi

TARGET_SOL="${VERIFIER_DIR}/src/${CONTRACT_NAME}.sol"
cp "${VERIFIER_SOL}" "${TARGET_SOL}"

GENERATED_CONTRACT_NAME="$(
  awk '
    /^[[:space:]]*contract[[:space:]]+[A-Za-z_][A-Za-z0-9_]*/ {
      name = $2
      sub(/[^A-Za-z0-9_].*$/, "", name)
      print name
      exit
    }
  ' "${TARGET_SOL}"
)"

if [[ -z "${GENERATED_CONTRACT_NAME}" ]]; then
  echo "Could not determine generated contract name from ${TARGET_SOL}" >&2
  exit 1
fi

TARGET_SOL_BASENAME="$(basename "${TARGET_SOL}")"
TARGET_CONTRACT_ID="src/${TARGET_SOL_BASENAME}:${GENERATED_CONTRACT_NAME}"
TARGET_ARTIFACT="${VERIFIER_DIR}/out/${TARGET_SOL_BASENAME}/${GENERATED_CONTRACT_NAME}.json"

if [[ "${CONTRACT_NAME}" != "${GENERATED_CONTRACT_NAME}" ]]; then
  echo "==> Keeping generated contract name ${GENERATED_CONTRACT_NAME} from ${TARGET_SOL}"
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required to inspect Foundry link references" >&2
  exit 1
fi

echo "==> Building verifier artifacts"
BUILD_OUTPUT="$(
  forge build --root "${VERIFIER_DIR}" --force 2>&1
)" || {
  printf '%s\n' "${BUILD_OUTPUT}" >&2
  exit 1
}

if [[ ! -f "${TARGET_ARTIFACT}" ]]; then
  echo "Could not find built artifact at ${TARGET_ARTIFACT}" >&2
  exit 1
fi

LINKED_LIBRARIES=()
while IFS= read -r LIBRARY_ID; do
  [[ -z "${LIBRARY_ID}" ]] && continue
  LINKED_LIBRARIES+=("${LIBRARY_ID}")
done < <(
  jq -r '
    .bytecode.linkReferences
    | to_entries[]?
    | .key as $src
    | .value
    | keys[]
    | "\($src):\(.)"
  ' "${TARGET_ARTIFACT}" | sort -u
)

LIBRARY_LINK_ARGS=()
for LIBRARY_ID in "${LINKED_LIBRARIES[@]}"; do
  [[ -z "${LIBRARY_ID}" ]] && continue

  echo "==> Deploying required library ${LIBRARY_ID}"
  LIBRARY_DEPLOY_OUTPUT="$(
    forge create \
      --root "${VERIFIER_DIR}" \
      --broadcast \
      --rpc-url "${RPC_URL}" \
      --private-key "${PRIVATE_KEY}" \
      "${LIBRARY_ID}" 2>&1
  )" || {
    printf '%s\n' "${LIBRARY_DEPLOY_OUTPUT}" >&2
    exit 1
  }
  printf '%s\n' "${LIBRARY_DEPLOY_OUTPUT}"

  LIBRARY_ADDRESS="$(
    printf '%s\n' "${LIBRARY_DEPLOY_OUTPUT}" | awk -F': ' '/Deployed to:/ { print $2; exit }'
  )"
  if [[ -z "${LIBRARY_ADDRESS}" ]]; then
    echo "Could not determine deployed address for ${LIBRARY_ID}" >&2
    exit 1
  fi

  LIBRARY_LINK_ARGS+=("${LIBRARY_ID}:${LIBRARY_ADDRESS}")
done

CREATE_ARGS=(
  --rpc-url "${RPC_URL}" \
  --private-key "${PRIVATE_KEY}" \
)

if [[ "${#LIBRARY_LINK_ARGS[@]}" -gt 0 ]]; then
  LIBRARIES_CSV="$(IFS=,; printf '%s' "${LIBRARY_LINK_ARGS[*]}")"
else
  LIBRARIES_CSV=""
fi

FINAL_BUILD_ARGS=(
  forge build
  --root "${VERIFIER_DIR}"
  --force
)

if [[ -n "${LIBRARIES_CSV}" ]]; then
  FINAL_BUILD_ARGS+=(--libraries "${LIBRARIES_CSV}")
fi

echo "==> Rebuilding linked verifier artifact"
FINAL_BUILD_OUTPUT="$(
  "${FINAL_BUILD_ARGS[@]}" 2>&1
)" || {
  printf '%s\n' "${FINAL_BUILD_OUTPUT}" >&2
  exit 1
}

DEPLOY_BYTECODE="$(jq -r '.bytecode.object' "${TARGET_ARTIFACT}")"
if [[ -z "${DEPLOY_BYTECODE}" || "${DEPLOY_BYTECODE}" == "null" ]]; then
  echo "Could not read linked deployment bytecode from ${TARGET_ARTIFACT}" >&2
  exit 1
fi

echo "==> Deploying ${GENERATED_CONTRACT_NAME} from ${TARGET_SOL}"
FINAL_SEND_OUTPUT="$(
  cast send \
    --async \
    "${CREATE_ARGS[@]}" \
    --create "${DEPLOY_BYTECODE}" 2>&1
)" || {
  printf '%s\n' "${FINAL_SEND_OUTPUT}" >&2
  exit 1
}
printf '%s\n' "${FINAL_SEND_OUTPUT}"

FINAL_TX_HASH="$(
  printf '%s\n' "${FINAL_SEND_OUTPUT}" | grep -Eo '0x[0-9a-fA-F]{64}' | head -n 1
)"
if [[ -z "${FINAL_TX_HASH}" ]]; then
  echo "Could not determine deployment transaction hash for ${GENERATED_CONTRACT_NAME}" >&2
  exit 1
fi

FINAL_RECEIPT_OUTPUT="$(
  cast receipt "${FINAL_TX_HASH}" --rpc-url "${RPC_URL}" 2>&1
)" || {
  printf '%s\n' "${FINAL_RECEIPT_OUTPUT}" >&2
  exit 1
}
printf '%s\n' "${FINAL_RECEIPT_OUTPUT}"

FINAL_CONTRACT_ADDRESS="$(
  printf '%s\n' "${FINAL_RECEIPT_OUTPUT}" | awk -F'  +' '/contractAddress/ { print $2; exit }'
)"
if [[ -z "${FINAL_CONTRACT_ADDRESS}" ]]; then
  echo "Could not determine deployed verifier address from receipt ${FINAL_TX_HASH}" >&2
  exit 1
fi

FINAL_CODE_SIZE="$(
  cast codesize "${FINAL_CONTRACT_ADDRESS}" --rpc-url "${RPC_URL}"
)" || {
  echo "Could not fetch deployed code size for ${FINAL_CONTRACT_ADDRESS}" >&2
  exit 1
}

if [[ "${FINAL_CODE_SIZE}" == "0" ]]; then
  echo "Deployment receipt succeeded but no runtime code found at ${FINAL_CONTRACT_ADDRESS}" >&2
  exit 1
fi

echo "==> Verifier deployed at ${FINAL_CONTRACT_ADDRESS} (${FINAL_CODE_SIZE} bytes)"
