[package]
name = "zus_protocol_starknet"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

[dependencies]
starknet = "2.8.2"

[dev-dependencies]
snforge_std = "0.58.0"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[cairo]
enable-gas = true

[[target.starknet-contract]]
sierra = true
casm = true
